rename config/db/ and var/sql/

diff --git a/bin/narada-mysql b/bin/narada-mysql
--- a/bin/narada-mysql
+++ b/bin/narada-mysql
@@ -4,12 +4,17 @@ VERSION='v1.4.5'
 warn()  { echo "$@" >&2;        }
 die()   { warn "$@"; exit 1;    }
 
-perl -MNarada -E 'Narada::detect(@ARGV)' || exit 1
+DETECT=$(perl -MNarada -E 'say Narada::detect(@ARGV)') || exit 1
+if test "$DETECT" = "narada"; then
+	config_dir='config/mysql'
+else
+	config_dir='config/db'
+fi
 
 [ $# -eq 0 ] || die "Usage: narada-mysql"
 
-if [ ! -s config/db/db ]; then
-    echo "ERROR: config/db/db absent or empty!"
+if [ ! -s "$config_dir/db" ]; then
+    echo "ERROR: $config_dir/db absent or empty!"
     exit
 fi
 
@@ -17,11 +22,11 @@ restore_umask=$(umask -p)
 umask 0077
 echo '[client]' > tmp/my.cnf.$$
 $restore_umask
-echo database   = "$(< config/db/db )"          >> tmp/my.cnf.$$
-echo user       = "$(< config/db/login )"       >> tmp/my.cnf.$$
-[ -s config/db/pass ] && echo password  = "$(< config/db/pass )" >> tmp/my.cnf.$$
-[ -s config/db/host ] && echo host      = "$(< config/db/host )" >> tmp/my.cnf.$$
-[ -s config/db/port ] && echo port      = "$(< config/db/port )" >> tmp/my.cnf.$$
+echo database   = "$(< "$config_dir/db" )"          >> tmp/my.cnf.$$
+echo user       = "$(< "$config_dir/login" )"       >> tmp/my.cnf.$$
+[ -s "$config_dir/pass" ] && echo password  = "$(< "$config_dir/pass" )" >> tmp/my.cnf.$$
+[ -s "$config_dir/host" ] && echo host      = "$(< "$config_dir/host" )" >> tmp/my.cnf.$$
+[ -s "$config_dir/port" ] && echo port      = "$(< "$config_dir/port" )" >> tmp/my.cnf.$$
 exec 3< tmp/my.cnf.$$
 rm tmp/my.cnf.$$
 exec mysql --defaults-file=/proc/self/fd/3 --pager=less\ -XSFe
@@ -51,17 +56,18 @@ This document describes narada-mysql version v1.4.5
 Should be executed in project deploy directory (or Narada 1.x project root
 directory).
 
-Start mysql client using connection details from config/db/*.
+Start mysql client using connection details from C<config/mysql/>.
 
 
 =head1 CONFIGURATION AND ENVIRONMENT
 
-Use files:
-  config/db/db
-  config/db/login
-  config/db/pass
-  config/db/host (optional)
-  config/db/port (optional)
+  config/mysql/db
+  config/mysql/login
+  config/mysql/pass
+  config/mysql/host (optional)
+  config/mysql/port (optional)
+
+Narada 1.x project use C<config/db/> instead of C<config/mysql/>.
 
 
 =head1 SUPPORT
